//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tandem.TandemIntegration {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TandemIntegration.TandemIntegration")]
    public interface TandemIntegration {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TandemIntegration/ReceiveXMLMessage", ReplyAction="http://tempuri.org/TandemIntegration/ReceiveXMLMessageResponse")]
        string ReceiveXMLMessage(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TandemIntegrationChannel : Tandem.TandemIntegration.TandemIntegration, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TandemIntegrationClient : System.ServiceModel.ClientBase<Tandem.TandemIntegration.TandemIntegration>, Tandem.TandemIntegration.TandemIntegration {
        
        public TandemIntegrationClient() {
        }
        
        public TandemIntegrationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TandemIntegrationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TandemIntegrationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TandemIntegrationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ReceiveXMLMessage(string message) {
            return base.Channel.ReceiveXMLMessage(message);
        }
    }
}
